Create UserMoneyService/Controller
YaroslavV1/LifeHelper pull request #18
Opened 2023-03-19 11:44 UTC by YaroslavV1

feat - Created UserMoneyService;
feat - Created UserMoneyController;
fix - Fixed namespace of User folder.

2023-03-23 09:25 UTC, Vladislawv requested changes

2023-03-23 09:25 UTC, Vladislawv commented on LifeHelper.Api/Controllers/UserMoneyController.cs
> +[Produces(MediaTypeNames.Application.Json)]
це шо ?

2023-03-23 09:25 UTC, Vladislawv commented on LifeHelper.Infrastructure/Entities/User.cs
> +            Money = 0
в 1 строку
не работает классическая привязка ?

2023-03-23 09:25 UTC, Vladislawv commented on LifeHelper.Services/Areas/UserMonies/DTOs/UserMoneyDto.cs
> +}
я бы назвал что-то около Amount, ибо Money уже есть в имени класса

2023-03-23 09:25 UTC, Vladislawv commented on LifeHelper.Services/Areas/UserMonies/UserMoneyService.cs
> +    }
в этом случае зайдёт метод расширения

2023-03-23 09:25 UTC, Vladislawv commented on LifeHelper.Services/Areas/UserMonies/UserMoneyService.cs
> +        decimal maxValue = 999_999_999.99m;
я думаю, тут можно юзать константы класса decimal

2023-03-23 09:25 UTC, Vladislawv commented on LifeHelper.Services/Areas/UserMonies/UserMoneyService.cs
> +    {
и тут тоже мейби amount в параметрах?

2023-03-23 09:25 UTC, Vladislawv commented on LifeHelper.Services/Areas/UserMonies/Validators/UserMoneyInputValidator.cs
> +    private const decimal MaximumValue = 999_999_999.99m;
консты тоже

2023-03-23 09:48 UTC, YaroslavV1 commented on LifeHelper.Api/Controllers/UserMoneyController.cs
> +[Produces(MediaTypeNames.Application.Json)]
Он берет из назавания контроллера имя, я понял, лучше хардом написать

2023-03-23 09:49 UTC, YaroslavV1 commented on LifeHelper.Infrastructure/Entities/User.cs
> +            Money = 0
тут не привязка, тут я хотел шоб при создании пользователя у нас создавался сразу UserMoney с дефолтными значениями в бд

2023-03-24 08:33 UTC, Vladislawv approved these changes

2023-03-24 08:33 UTC, Vladislawv commented on LifeHelper.Services/Areas/UserMonies/UserMoneyService.cs
можно без of в принципе

2023-03-24 08:33 UTC, Vladislawv commented on LifeHelper.Services/Areas/UserMonies/Validators/UserMoneyInputValidator.cs
> +    private const decimal MaximumAmount = 999_999_999.99m;
здесь Minimum, а в сервисе Min - к чему-то одному прийди (лучше без скоращний)

2023-03-24 10:54 UTC, merged